name: Build and Deploy
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: vuepress-deploy
              uses: jenkey2011/vuepress-deploy@master
              env:
                  ACCESS_TOKEN: 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
                  TARGET_REPO: mebe-odoo/mebe-odoo.github.io
                  TARGET_BRANCH: main
                  BUILD_SCRIPT: yarn && yarn docs:build
                  BUILD_DIR: docs/.vuepress/dist
                  CNAME: https://mebe-odoo.github.io
